package com.ibm.ecm.extension.countfilter;

import javax.servlet.http.HttpServletRequest;

import com.ibm.ecm.extension.PluginResponseFilter;
import com.ibm.ecm.extension.PluginServiceCallbacks;
import com.ibm.json.java.JSONArray;
import com.ibm.json.java.JSONObject;
import com.ibm.mm.sdk.common.DKDocRoutingServiceICM;
import com.ibm.mm.sdk.common.DKDocRoutingServiceMgmtICM;
import com.ibm.mm.sdk.common.DKSequentialCollection;
import com.ibm.mm.sdk.common.DKWorkListICM;
import com.ibm.mm.sdk.common.dkIterator;
import com.ibm.mm.sdk.server.DKDatastoreICM;

/**
 * Provides an abstract class that is extended to create a filter for responses
 * from a particular service. The response from the service is provided to the
 * filter in JSON format before it is returned to the web browser. The filter
 * can then modify that response, and the modified response is returned to the
 * web browser.
 */
public class WorklistCountResponseFilter extends PluginResponseFilter {

	/**
	 * Returns an array of the services that are extended by this filter.
	 * 
	 * @return A <code>String</code> array of names of the services. These are
	 *         the servlet paths or Struts action names.
	 */
	public String[] getFilteredServices() {
		return new String[] { "/cm/getWorklists","/cm/getWorkItems" };
	}

	/**
	 * Filters the response from the service.
	 * 
	 * @param serverType
	 *            A <code>String</code> that indicates the type of server that
	 *            is associated with the service. This value can be one or more
	 *            of the following values separated by commas:
	 *            <table border="1">
	 *            <tr>
	 *            <th>Server Type</th>
	 *            <th>Description</th>
	 *            </tr>
	 *            <tr>
	 *            <td><code>p8</code></td>
	 *            <td>IBM FileNet P8</td>
	 *            </tr>
	 *            <tr>
	 *            <td><code>cm</code></td>
	 *            <td>IBM Content Manager</td>
	 *            </tr>
	 *            <tr>
	 *            <td><code>od</code></td>
	 *            <td>IBM Content Manager OnDemand</td>
	 *            </tr>
	 *         	  <tr>
	 *         		<td><code>cmis</code></td>
	 *         		<td>Content Management Interoperability Services</td>
	 *         	  </tr>
	 *            <tr>
	 *            <td><code>common</code></td>
	 *            <td>For services that are not associated with a particular
	 *            server</td>
	 *            </tr>
	 *            </table>
	 * @param callbacks
	 *            An instance of the
	 *            <code>{@link com.ibm.ecm.extension.PluginServiceCallbacks PluginServiceCallbacks}</code>
	 *            class that contains functions that can be used by the service.
	 *            These functions provide access to plug-in configuration and
	 *            content server APIs.
	 * @param request
	 *            An <code>HttpServletRequest</code> object that provides the
	 *            request. The service can access the invocation parameters from
	 *            the request.
	 * @param jsonResponse
	 *            The <code>JSONObject</code> object that is generated by the
	 *            service. Typically, this object is serialized and sent as the
	 *            response. The filter modifies this object to change the
	 *            response that is sent.
	 * @throws Exception
	 *             For exceptions that occur when the service is running.
	 *             Information about the exception is logged as part of the
	 *             client logging and an error response is automatically
	 *             generated and returned.
	 */
	public void filter(String serverType, PluginServiceCallbacks callbacks,
			HttpServletRequest request, JSONObject jsonResponse) throws Exception {
		System.out.println("jsonResponse in CountResponseFilter = "+jsonResponse);
		//System.out.println("jsonResponse size = "+jsonResponse.size());
		String requestName = request.getParameter("worklist_name");
		System.out.println("WL Req="+ requestName);
		DKDatastoreICM dsICM = null;    
		
		//dsICM = callbacks.getCMDatastore("cm");
		dsICM = callbacks.getCMDatastore("CMRepository");

		System.out.println("jsonResponse size = "+jsonResponse.size());
		//System.out.println("jsonData size = "+jsonData.size());
		
		if(requestName==null){
		DKDocRoutingServiceICM routingService = new DKDocRoutingServiceICM(dsICM);   
		DKDocRoutingServiceMgmtICM routingMgmt = new DKDocRoutingServiceMgmtICM(dsICM);
		
		
		 DKSequentialCollection workLists = (DKSequentialCollection) routingMgmt.listWorkLists();
			
		 //String requestName = request.getParameter("worklist_name");
		 //String realName = "";
		 //String wlname = "";
		 System.out.println("userid = "+callbacks.getUserId());
		 //System.out.println("dsICM = "+dsICM);
		 JSONObject jsonData = (JSONObject)jsonResponse.get("datastore");
		 System.out.println("jsonData size = "+jsonData.size());
		 System.out.println("jsonData  = "+jsonData);
		 JSONArray jsonItems = (JSONArray)jsonData.get("items");
			
		 dkIterator iter = workLists.createIterator();
		 
		 DKWorkListICM workList; 
		 while (iter.more()) { // loop each worklist 
	        workList = (DKWorkListICM) iter.next();
		    //System.out.println("requestName="+requestName);
		    //System.out.println("workList.getName()="+workList.getName());
		    for(int i = 0; i < jsonItems.size(); i++){
            	
				JSONObject jsonWorkList = (JSONObject)jsonItems.get(i);
				//System.out.println("get worklist_name = "+(String)jsonWorkList.get("worklist_name"));
				
				if (workList.getName().equalsIgnoreCase((String)jsonWorkList.get("worklist_name").toString().trim())) {
					//System.out.println("get owner = "+workList.getSelectionFilterOnOwner()+callbacks.getUserId());
					//System.out.println("get count = "+routingService.getCount(workList.getName(),callbacks.getUserId()));
					
					//lista..SelectionFilterOnOwner(DKConstantICM.DK_ICM_DR_SELECTION_FILTER_YES);
					String name = workList.getName() + " (" + routingService.getCount(workList.getName(),callbacks.getUserId()) + ")";
					jsonWorkList.put("worklist_name", name);
				}
			}
		 }
	}
	}
}
